# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Glosujacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=20)),
                ('licznik', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10)),
                ('maxKandydatow', models.IntegerField(default=0)),
                ('czasWyboru', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='kandydat',
            name='partia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doggo.Partia'),
        ),
        migrations.AddField(
            model_name='kandydat',
            name='wybory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doggo.Wybory'),
        ),
        migrations.AddField(
            model_name='glos',
            name='glosujacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doggo.Glosujacy'),
        ),
        migrations.AddField(
            model_name='glos',
            name='wybory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doggo.Wybory'),
        ),
    ]
