# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doggo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doggo.Kandydat')),
                ('wybory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doggo.Wybory')),
            ],
        ),
    ]
