# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doggo', '0002_kandydowanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wybory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
