# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doggo', '0003_auto_20170517_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='glosujacy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='glosujacy',
            name='pesel',
            field=models.BigIntegerField(unique=True, verbose_name=11),
        ),
    ]
